name: Deploy to logistics1 via SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP (optional)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install composer deps (prod)
        run: |
          if [ -f composer.json ]; then
            composer install --no-dev --no-interaction --no-progress --prefer-dist
          else
            echo "No composer.json, skipping composer install."
          fi

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.FTP_SERVER }}       # 23.94.230.146
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port:     ${{ secrets.FTP_PORT }}         # 22
          source:   "./"
          target:   "/home/Logis798gx/logistics1.viahale.com/"   # adjust if your root is /public_html/
          overwrite: true
          rm: false
          strip_components: 0

      - name: Verify files on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.FTP_SERVER }}       # 23.94.230.146
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port:     ${{ secrets.FTP_PORT }}
          script: |
            echo "Deployed files:"
            ls -la "/home/Logis798gx/logistics1.viahale.com/" | head -n 20
