name: CI → Test → Build → Deploy

on:
  push:
    branches: [ "staging", "main" ]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- PHP setup + Composer ----------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpunit

      - name: Install Composer deps (prod for main, dev for staging)
        run: |
          if [ -f composer.json ]; then
            if [ "${{ github.ref_name }}" = "main" ]; then
              composer install --no-dev --no-interaction --no-progress --prefer-dist
            else
              composer install --no-interaction --no-progress --prefer-dist
            fi
          else
            echo "No composer.json, skipping composer."
          fi

      # ---------- PHP lint (basic test) ----------
      - name: PHP syntax check
        run: |
          mapfile -t FILES < <(find . -type f -name "*.php")
          if [ ${#FILES[@]} -gt 0 ]; then
            for f in "${FILES[@]}"; do php -l "$f"; done
          else
            echo "No PHP files found to lint."
          fi

      # ---------- PHPUnit (if configured) ----------
      - name: Run PHPUnit (if phpunit.xml exists)
        run: |
          if [ -f phpunit.xml ] || [ -f phpunit.xml.dist ]; then
            vendor/bin/phpunit --colors=always
          else
            echo "No phpunit config, skipping tests."
          fi

      # ---------- Node build (optional) ----------
      - name: Setup Node (only if package.json exists)
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          npm ci || npm install

      - name: Build front-end
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          # try common build scripts; no-op if none exist
          if npm run | grep -q " build"; then
            npm run build
          else
            echo "No npm build script, skipping."
          fi

      # ---------- Package artifact (optional) ----------
      - name: Archive build artifact
        run: |
          tar -czf site.tar.gz \
            --exclude='./.git' \
            --exclude='./.github' \
            --exclude='./node_modules' \
            --exclude='./tests' \
            --exclude='./README.md' \
            --exclude='./composer.lock' \
            --exclude='./package*.json' \
            .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: ${{ success() }}    # only deploy if build_and_test passed

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Extract
        run: tar -xzf site.tar.gz

      # ---- choose server-dir by branch: staging vs main ----
      - name: Set target directory
        id: paths
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "dir=/home/Logis798gx/logistics1.viahale.com/" >> $GITHUB_OUTPUT
          else
            # deploy staging to a subfolder (create once in File Manager)
            echo "dir=/home/Logis798gx/logistics1.viahale.com/staging/" >> $GITHUB_OUTPUT
          fi

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}            # 23.94.230.146
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port:     21
          protocol: ftps
          security: loose
          timeout: 60000
          local-dir: ./                                  # the extracted archive
          server-dir: ${{ steps.paths.outputs.dir }}     # live or staging
          dangerous-clean-slate: false
          exclude: |
            **/.git**
            **/.github/**
            **/node_modules/**
            **/tests/**
            .env
            README.md
            composer.lock
            package*.json
