name: Deploy to logistics1 via SFTP

on:
  push:
    branches: [ "main" ]      # deploy when pushing to main
  workflow_dispatch: {}        # allow manual runs from Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP (optional)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install composer deps (prod)
        run: |
          if [ -f composer.json ]; then
            composer install --no-dev --no-interaction --no-progress --prefer-dist
          else
            echo "No composer.json, skipping composer install."
          fi

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.FTP_SERVER }}      # sftp.logistics1.viahale.com
          username: ${{ secrets.FTP_USERNAME }}    # your CyberPanel FTP user
          password: ${{ secrets.FTP_PASSWORD }}
          port:     22
          source:   "./"
          target:   "/home/Logis798gx/logistics1.viahale.com/"   # or /public_html if that's your doc root
          overwrite: true
          rm: false
          strip_components: 0

      # Optional: confirm deployment
      - name: List deployed files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port:     22
          script: |
            echo "Deployment completed. Showing top files:"
            ls -la "/home/Logis798gx/logistics1.viahale.com/" | head -n 20
